version: '3.8'
services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:${DB_PORT}'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car-rental-backend
    environment:
      - PORT=${PORT}
      - DOCKER=true
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    volumes:
      - ./src:/app/src